name: Reusable WF - Nightly Pytest Run

on:
  workflow_dispatch:  # Optional manual trigger
  schedule:
    - cron: 0 4 * * *  # Run nightly at 12am Raleigh time (EST)
  push:
    branches:
      - main  # Run on every push to main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    name: Pytest (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run unit tests
        run: |
          python --version
          pip install -r requirements.in
          pip install -r requirements-dev.in
          loglevel=${1:-INFO}
          python -m pytest -s --log-cli-level=${loglevel} -o junit_family=xunit2 --junitxml=junit/test-results.xml